MyFirstForum/Models/Forum/ForumIndexModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyFirstForum.Models.Forum
{
    public class ForumIndexModel
    {
        public IEnumerable<ForumListingModel> ForumList { get; set; }
    }
}

MyFirstForum/Models/Forum/ForumListingModel.cs
namespace MyFirstForum.Models.Forum
{
    public class ForumListingModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
    }
}

MyFirstForum/Models/Forum/ForumTopicModel.cs
using MyFirstForum.Models.Post;
using System.Collections.Generic;

namespace MyFirstForum.Models.Forum
{
    public class ForumTopicModel
    {
        public ForumListingModel Forum { get; set; }
        public IEnumerable<PostListingModel> Posts { get; set; }
    }
}

MyFirstForum/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyFirstForum.Data;
using MyFirstForum.Data.Models;
using MyFirstForum.Models.Forum;
using MyFirstForum.Models.Post;

namespace MyFirstForum.Controllers
{
    public class ForumController : Controller
    {
        private readonly IForum _forumService;

        public ForumController(IForum forumService)
        {
            _forumService = forumService;
        }

        public IActionResult Index()
        {
            var forums = _forumService.GetAll()
                .Select(forum => new ForumListingModel {
                    Id = forum.Id,
                    Name = forum.Title,
                    Description = forum.Description
            });

            var model = new ForumIndexModel
            {
                ForumList = forums
            };

            return View(model);
        }

        public IActionResult Topic(int id)
        {
            var forum = _forumService.GetById(id);
            var posts = forum.Posts;


            var postListings = posts.Select(post => new PostListingModel
            {
                Id = post.Id,
                AuthorId = post.User.Id,
                AuthorRating = post.User.Rating,
                Title = post.Title,
                DatePosted = post.Created.ToString(),
                RepliesCount = post.Replies.Count(),
                Forum = BuildForumListing(post)

            });

            var model = new ForumTopicModel
            {
                Posts = postListings,
                Forum = BuildForumListing(forum)
            };

            return View(model);
        }

        private ForumListingModel BuildForumListing(Post post)
        {
            var forum = post.Forum;
            return BuildForumListing(forum);
        }

        private ForumListingModel BuildForumListing(Forum forum)
        {
            return new ForumListingModel
            {
                Id = forum.Id,
                Name = forum.Title,
                Description = forum.Description,
                ImageUrl = forum.ImageUrl
            };
        }
    }
}

MyFirstForum/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyFirstForum.Data;

namespace MyFirstForum.Controllers
{
    public class PostController : Controller
    {
        private readonly IPost _postService;

        public PostController(IPost postService)
        {
            _postService = postService;
        }

        public IActionResult Index(int id)
        {
            var post = _postService.GetById(id);

            return View();
        }
    }
}

MyFirstForum/Views/Forum/Index.cshtml
@model MyFirstForum.Models.Forum.ForumIndexModel

<h1>Forums</h1>

<table class="table table-hover" id="forumIndexTable">
    <tbody>
        @foreach (var forum in Model.ForumList)
        {
            <tr>
                <td>
                    <a asp-controller="Forum" asp-action="Topic" asp-route-id="@forum.Id">
                        @forum.Name
                    </a>
                    
                </td>
                <td>
                    @forum.Description
                </td>
            </tr>
        }
    </tbody>
</table>

MyFirstForum/Views/Forum/Topic.cshtml
@model MyFirstForum.Models.Forum.ForumTopicModel

<h1>Welcome to the @Model.Forum.Name Forum!</h1>

@if (Model.Posts.Any())
{
    <table class="table table-bordered table-hover">
        <tbody>
            @foreach (var post in Model.Posts)
            {
                <tr>
                    <td>
                        <a asp-controller="Post" asp-action="Index" asp-route-id="@post.Id">
                            @post.Title
                        </a>
                    </td>
                    <td>
                        @post.Author
                    </td>
                    <td>
                        @post.DatePosted
                    </td>
                    <td>
                        @post.RepliesCount
                    </td>
                </tr>
            }
        </tbody>
    </table>
 }

else {
    <div class="noPosts">
        <h3>
            It looks like there are no @Model.Forum.Name posts yet... <br />
            Why not 
            <a asp-controller="Post" asp-action="Create" asp-route-id="@Model.Forum.Id">
                <span>create</span>
            </a>
            one?
        </h3>
    </div>
 }